export class Constantes {
  public static OPTIONS_CONFIG = 'options';
  public static CONECTION_DATABASE = 'SMARTSOFT_DATABASE_CONNECTION';
  public static TABLE_REPOSITORY = "TABLE_REPOSITORY";
  public static TABLE_STRUCTURE_REPOSITORY = "TABLE_STRUCTURE_REPOSITORY";
  public static TABLE_DATA_ONE_REPOSITORY = "TABLE_DATA_ONE_REPOSITORY";
  public static TABLE_DATA_TWO_REPOSITORY = "TABLE_DATA_TWO_REPOSITORY";
  public static TABLE_DATA_THREE_REPOSITORY = "TABLE_DATA_THREE_REPOSITORY";
}